<?php

namespace Database\Seeders;

use App\Models\Fabricante;
use Illuminate\Database\Seeder;

class FabricanteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $fabricantes = [
            '3M',
            'Abracon Corporation',
            'ACS Inc.',
            'Adamtech',
            'Adda',
            'Alpha&Omega Semiconductor',
            'Alphatex Corporation',
            'AlphaWire',
            'Alps',
            'Amethern',
            'Amphenol',
            'Amphenol Spectra-Strip',
            'Amprobe',
            'Analog Devices Inc.',
            'APC',
            'API Delavan',
            'Atmel',
            'Avago Technologies',
            'Avx Corporation',
            'B&K Precision',
            'Bei Sensors',
            'Bel Fuse Inc.',
            'BI Technologies',
            'Bivar',
            'Bourns Inc.',
            'Bud Industries',
            'C&K Components',
            'C&K Electronics',
            'Central Semiconductor',
            'Cherry Electrical',
            'Chicago Miniature',
            'Clare',
            'Comchip Technology',
            'Cooper Bussmann',
            'Cornell Dubilier Electronics',
            'Crouzet USA',
            'Crydom',
            'Crystek Corporation',
            'CTS Corporation',
            'CTS Electrocomponents',
            'CUI Inc.',
            'Cypress Semiconductors',
            'Daburn Electronics',
            'Desco',
            'Digi International',
            'Diodes/Zetex',
            'Diodes Inc.',
            'Ebm-Papst',
            'ECS Inc.',
            'Elna America',
            'Energizer Battery Company',
            'Epcos Inc.',
            'Epson Toyocom Corporation',
            'Everlight',
            'Extech',
            'Fairchild Semiconductor',
            'FCI',
            'Fluke Electronics',
            'Fox Electronics',
            'Freescale Semiconductor',
            'GE Sensing',
            'Grayhill Inc.',
            'Hammond Manufacturing',
            'Harting',
            'Harwin Inc.',
            'Hirose Electric',
            'Honeywell',
            'Honeywell/Microswitch',
            'Infineon Technologies',
            'International Rectifier',
            'Ixys',
            'Johanson',
            'JW Miller',
            'Kemet',
            'Keystone Electronics',
            'Koa Speer',
            'Laird Technologies',
            'Lattice',
            'Lecroy',
            'Linear Technology',
            'Linx Technologies',
            'Littelfuse Inc.',
            'Makita',
            'Maxim Integrated Products',
            'MCC-Micro Commercial Components',
            'Mean Well',
            'Memory Protection Devices',
            'Microchip Technology',
            'Microsemi',
            'Molex Connector',
            'Murata Electronics',
            'Murata Power Solutions',
            'Nichicon',
            'NJR–New Japan Radio',
            'NXP Electronics',
            'NXP Semiconductors',
            'Ohmite',
            'OK International',
            'Omron Electronics Inc.',
            'ON Semiconductor',
            'Optrex America Inc.',
            'Orion Fans',
            'Osram Opto Semiconductor',
            'Pamoma Electronics',
            'Panasonic',
            'Panasonic-ECG',
            'Panasonic–Bsg',
            'Panduit Corp.',
            'Parallax',
            'Parlex Corp',
            'Phoenix Contact',
            'Protek',
            'PUI Audio Inc.',
            'Pulse',
            'Red Lion Controls',
            'Renesas Electronics',
            'Richco',
            'Rohm Semiconductor',
            'Schurter Inc.',
            'SEI–Stackpole Electronics Inc.',
            'Seiko Instruments',
            'Sharp Microelectronics',
            'Shindengen',
            'SL Power',
            'Spectrum Sensor',
            'ST Microelectronics',
            'Sumida',
            'Susumu',
            'Tadiram Batteries',
            'Taiyo Yuden',
            'Tamura',
            'TDK–Lambda',
            'TDK Corporation',
            'TE Connectivity',
            'Tektronix',
            'Teledyne Relays',
            'Texas Instruments',
            'Toshiba',
            'Tripp Lite',
            'Tri Quint Semiconductor',
            'United Chemi-Con',
            'Vector Electronics',
            'Viking America',
            'Vishay',
            'Vishay/BC Components',
            'Vishay/Dale',
            'Vishay/Sprague',
            'Vishay/Vitramon',
            'Vishay Semiconductors',
            'Weidmuller',
            'Wurth Electronics Inc.',
            'Yageo',
        ];

        foreach ($fabricantes as $value) {
            Fabricante::create(['nome' => $value]);
        }
    }
}
